name: Deploy to Google Cloud Functions

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Authenticate with Google Cloud
    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    # Step 5: Deploy to Google Cloud Functions
    - name: Deploy to Google Cloud Functions
      run: |
        gcloud functions deploy cf-at-bq-dials \
          --runtime python311 \
          --trigger-http \
          --allow-unauthenticated \
          --entry-point post_to_bigquery_with_timestamp \
          --region us-central1 \
          --project ${{ secrets.GCP_PROJECT_ID }} \
          --set-env-vars BIGQUERY_TABLE_ID=${{ secrets.BIGQUERY_TABLE_ID }},LOG_EXECUTION_ID=${{ secrets.LOG_EXECUTION_ID }}
